version: '3.8'

services:
  loggen:
    build: ./loggen
    container_name: loggen
    networks:
      - logging-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - logging-network
    healthcheck:
      test: curl -s http://localhost:9200/_cluster/health | grep -q '"status":"green"\|"status":"yellow"'
      interval: 10s
      timeout: 10s
      retries: 5

  vector:
    build: ./vector
    container_name: vector
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - logging-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - logging-network

networks:
  logging-network:
    driver: bridge

volumes:
  es_data: 